name: Python Inspector

on:
  # push:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Print python and pip versions
        run: |
          python --version
          pip --version

      - name: Print Python binary location
        run: command -v python

      - name: Finish inspection
        run: echo "Inspection complete"